# Rasio Dosen dan Mahasiswa

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(readxl)
library(dplyr, warn.conflicts = F)
library(tidyverse)

dos_pns <- read.csv("G:/My Drive/# REGISTRASI DAN STATISTIK/DATA PEGAWAI/DOSEN PNS/Update/update_dos_pns.csv")
dos_pns <- dos_pns[, c(11, 12)]
names(dos_pns) <- c("Fakultas", "Prodi")

dos_non <- read.csv("G:/My Drive/# REGISTRASI DAN STATISTIK/DATA PEGAWAI/DOSEN PNS/Update/update_dos_non_pns.csv")
dos_non <- dos_non[, c(7, 13)]
names(dos_non) <- c("Fakultas", "Prodi")


dosen <- rbind.data.frame(dos_pns, dos_non)
dosen$Prodi <- toupper(dosen$Prodi)
dosen <- dosen %>%
  group_by(Fakultas, Prodi) %>%
  summarise(n = n(), .groups = "drop")

dosen[dosen == "PENDIDIKAN ANAK USIA DINI"] <- "PENDIDIKAN GURU PENDIDIKAN ANAK USIA DINI"
dosen[dosen == "PENDIDIKAN GURU SD"] <- "PENDIDIKAN GURU SEKOLAH DASAR"

aktif <- read_excel("static/aktif.xlsx")
aktif <- aktif[, c(3, 5, 6)]
aktif <- aktif %>%
  group_by(Fakultas, Prodi, Jenjang) %>%
  summarise(n = n(), .groups = "drop") %>%
  filter(Fakultas != "Pascasarjana")

rasio <- left_join(aktif, dosen, by = c("Fakultas", "Prodi"))

rasio$ras <- paste0("1 : ", round(rasio$n.x/rasio$n.y, digits = 0))

fak <- data.frame(
  Fakultas = c("Hukum", "FKIP", "Teknik", "Pertanian", "FEB", "FISIP", "Kedokteran"),
  urutan = 1:7
)

rasio <- rasio %>%
  left_join(fak, by = "Fakultas") %>%
  arrange(urutan) %>%
  select(-urutan)



#rasio <- read_excel("static/rasio.xlsx")

```

Secara keseluruhan, rasio dosen dan mahasiswa di untirta adalah 1 : `r round(sum(rasio$n.x)/sum(rasio$n.y, na.rm = T), 0)`. Rasio dosen dan mahasiswa ideal untuk rumpun sosial adalah 1 : 45 dan untuk rumpun sains adalah 1 : 30. Berikut adalah rasio dosen dan mahasiswa Universitas Sultan Ageng Tirtayasa di setiap Program Studi.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
names(rasio) <- c("Fakultas", "Jenjang", "Program Studi", "Mahasiswa", "Dosen", "Rasio")
library(kableExtra)
kable(rasio[, -1], row.names = F) %>%
  kable_styling(bootstrap_options = "striped", full_width = F,
                latex_options = "scale_down") %>%
  pack_rows("Hukum", 1, 1, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Keguruan dan Ilmu Pendidikan", 2, 19, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Teknik", 20, 26, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Pertanian", 27, 30, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ekonomi dan Bisnis", 31, 38, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Ilmu Sosial dan Ilmu Politik", 39, 41, label_row_css = "background-color: #666; color: #fff;") %>%
  pack_rows("Kedokteran", 42, 46, label_row_css = "background-color: #666; color: #fff;")


```
